### ISSUE TITLE
No releases available

### ISSUE THREAD

**Issue by Valmelma07** [xAfterLife/Eris#28]
The Readme says
> "To install Eris, simply download the latest version from the releases page and run the executable. The updater will handle the rest, downloading and installing the necessary files for your private server."

However, there are no releases, and no other way to contact except opening an issue.
Is this project still being worked on?

**Comment by xAfterLife** [comment]
Hey, sadly this Repo was inactive for quite a while.
Since the WpfUI Library used here received some breaking changes and gets merged into .NET 9 itself I'll wait till that merge is complete.
Development on this will resume again then.
